#!/bin/sh

update_db_setups() {
    rsync -av --delete ../contactopensource_with_postgresql/db/setups/ db/setups/
}

update_db_generators() {
    pushd db/generators
    ./renumber
    popd
}

update_db_setups
update_db_generators